### ISSUE TITLE
Возвращаемое значение метода lookup может быть 3 разных типов

### ISSUE THREAD

**Issue by heroboec** [LeakCheck/leakcheck-api#1]
Метод может вернуть list, Exception, JSONDecodeError. 
Это делает отвратительным написание нормального кода, который бы использовал данную библиотеку. Для того, чтобы ничего не упало при использовании библиотеки приходится делать проверки на тип возвращаемого значения.

Exception в методе lookup вообще не обрабатывается блоком "except" а передается как возвращаемое значение - это достаточно странное использование исключений. Если Вы ничего с ними не делаете, то просто отдавайте их выше в дерево вызовов, не нужно их ловить, обработкой пусть занимается вызывающий код.

**Comment by LeakCheck** [comment]
Исправлено в версии 0.1.3, https://github.com/LeakCheck/leakcheck-api/commit/24e8945029b75a9b5ac1191bdc65c543237256d6
