### ISSUE TITLE
Поле self.result не очищается при повторном вызове lookup

### ISSUE THREAD

**Issue by heroboec** [LeakCheck/leakcheck-api#2]
Если вызывающий код поместит вызов lookup в цикл, а это очевидный вариант использования, то данные ответа на запрос будут постоянно добавляться  к предыдущим, находящимся в поле self.result.

**Comment by LeakCheck** [comment]
Исправлено в версии 0.1.3, https://github.com/LeakCheck/leakcheck-api/commit/24e8945029b75a9b5ac1191bdc65c543237256d6
